# Generated by Django 5.0.3 on 2024-03-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
