# Generated by Django 5.0.3 on 2024-03-18 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employe_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
                ('jobdesc', models.TextField()),
                ('salary', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Mason', 'Mason'), ('Floor-worker', 'Floor-worker'), ('Helper', 'Helper'), ('Construction-worker', 'Construction-worker'), ('Carpenter', 'Carpenter'), ('Welder', 'Welder')], max_length=30)),
                ('contact_details', models.CharField(max_length=50)),
                ('cjob_img', models.ImageField(blank=True, null=True, upload_to='jobs')),
                ('is_available', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
